require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/version" #'ankusa/version'
require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/extensions" #'ankusa/extensions'
require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/classifier" #'ankusa/classifier'
require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/naive_bayes" #'ankusa/naive_bayes'
require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/kl_divergence" #'ankusa/kl_divergence'
require "#{APP_PATH}/backend/lib/ankusa/lib/ankusa/hasher" #'ankusa/hasher'